<?php

namespace AppBundle\Repository;

/**
 * ProjectPlatformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectPlatformRepository extends \Doctrine\ORM\EntityRepository
{
}
